### ISSUE TITLE
GCCPUFraction Gauge crashes dashboard

### ISSUE THREAD

**Issue by bygui86** [dche423/temi#2]
As I wrote already in the [comments](https://medium.com/p/3b9f83f363a8/responses/show) of [your article](https://levelup.gitconnected.com/building-a-terminal-dashboard-in-golang-in-300-lines-of-code-3b9f83f363a8), there is a problem with your dashboard.
It seems that `GCCPUFraction: widgets.NewGauge()` crashes the whole dashboard.

Can you help me?

**Comment by dche423** [comment]
hi there, maybe you could paste the crash stacktrace  here. It would help to investigate the issue

**Comment by bygui86** [comment]
That's the real problem. I can't get any stacktrace or logs.
Right after starting the dashboard with the command `go run main.go -url http://localhost:6060/debug/vars`, the dashboard crashes and leaves just a completely black screen like below.

![screen-1](https://user-images.githubusercontent.com/22518997/76521161-8dfe9380-6464-11ea-84af-3aab1a80e98a.png)

Then if I have a look at go-processes running with `gops`, I see and kill the dashboard (named "go" with PID "49200") but it somehow survive and presents some other weird logs. Checking again with `gops` it appears a second running application (named "main" with PID "49227"). 

![screen-2](https://user-images.githubusercontent.com/22518997/76521369-fea5b000-6464-11ea-96ed-8ca3bb869d68.png)

After killing the second application, the dashboard definitely stops.

![screen3](https://user-images.githubusercontent.com/22518997/76521386-05ccbe00-6465-11ea-819e-8ff91de00b6c.png)

**Comment by dche423** [comment]
It looks like an issue related to the shell and has nothing to do with the program.

To verify this guess you can try two things:

1.  `go build` then run the standalone output binary
2. or just debug it in some IDE,  by doing so  you can isolate the execution environment from the shell

**Comment by bygui86** [comment]
Thank you :) I will try to build and run the standalone binary and using JetBrains Goland to debug.

**Comment by bygui86** [comment]
Till now I tried just `go build`, same crash :(

**Comment by bygui86** [comment]
and through the IDE this is what I see

<img width="1152" alt="Screenshot 2020-03-20 at 21 16 05" src="https://user-images.githubusercontent.com/22518997/77206972-868c5980-6af8-11ea-81b0-b1af62776f53.png">

no other logs...

**Comment by dche423** [comment]
see https://github.com/dche423/temi/pull/3
